font_family      Sarasa Mono SC
font_size        12.0

text_composition_strategy legacy

scrollback_lines 10000

enable_audio_bell no

confirm_os_window_close 0

tab_bar_edge        top
tab_bar_style      separator
tab_bar_min_tabs   1
tab_separator      " "
tab_title_template "{index}: {title}"

shell_integration no-cursor

window_border_width 3pt
inactive_text_alpha 0.6

strip_trailing_spaces smart

# 点击链接需要按住 ctrl（覆盖默认的直接点击打开行为）
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link

clipboard_control write-clipboard write-primary read-clipboard read-primary

repaint_delay 8
input_delay   2

include ./light-modern.conf
